version: '3'
services:

  admin:

    build: ./admin
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgresql
    volumes:
      - staticfiles:/admin/staticfiles

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  staticfiles:
  postgresql_data:
  