@startuml
skinparam componentStyle uml2
actor Client #line:black
component "Administration\nService" as AdminService #line:orange
component "ETL\nPostgres\nto Elastic" as ETL_PG_ES #line:blue
component "Movies\nService" as Movies
component "Auth\nService" as Auth #line:green

database Postgres
database Redis
database Elastic


Client -[#green]> Auth: "Аутентификация / Регистрация\nклиента"
Auth -[#green]-> Postgres: "Сохранение клиента в базу"
Auth -[#green]> Client: "Access и Refresh токены"
Auth -[#green]> Redis: "Сохранение истекших\nRefresh токенов"

Client --> Movies: "Запрос контента"
Client <-- Movies: "Получение контента"
Movies -> Auth: "Проверка токена\nи прав пользователя"
Movies --> Redis: "Сохранение / проверка кэша"
Movies --> Elastic: "Запрос данных"

Postgres <-[#blue]- ETL_PG_ES: "Запрос новых / обновлённых данных"
Redis <-[#blue]- ETL_PG_ES : "Сохранение состояния"
ETL_PG_ES -[#blue]-> Elastic: "Загрузка новых / обновлённых данных"

Postgres <-[#orange] AdminService: "Загрузка контента в базу"
@enduml