version: '3'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000"
    volumes:
      - ./:/opt/app

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200"
    volumes:
      - data:/var/lib/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 5000M

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379"

  etl:
    container_name: etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./etl:/etl
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - api
    restart: on-failure

volumes:
  data:
