"""empty message

Revision ID: 001_initial
Revises: 
Create Date: 2023-05-03 17:38:48.638410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('account_entrance',
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('entrance_date', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('ip_addr', sa.String(length=64), nullable=False),
    sa.Column('user_auth_service', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('platform', 'id'),
    sa.UniqueConstraint('id', 'platform'),
    postgresql_partition_by='LIST (platform)'
    )
    op.execute("""CREATE TABLE IF NOT EXISTS "account_entrance_windows" PARTITION OF "account_entrance" FOR VALUES IN ('windows')""")
    op.execute("""CREATE TABLE IF NOT EXISTS "account_entrance_linux" PARTITION OF "account_entrance" FOR VALUES IN ('linux')""")
    op.execute("""CREATE TABLE IF NOT EXISTS "account_entrance_macos" PARTITION OF "account_entrance" FOR VALUES IN ('macos')""")
    op.execute("""CREATE TABLE IF NOT EXISTS "account_entrance_other" PARTITION OF "account_entrance" FOR VALUES IN ('other')""")
    op.create_table('refresh_token',
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('user', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_social',
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('social_user_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_social')
    op.drop_table('refresh_token')
    op.drop_table('account_entrance')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
