"""empty message

Revision ID: 94464353ea8a
Revises: c24531f9bfc3
Create Date: 2023-05-01 15:18:39.331427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94464353ea8a'
down_revision = 'c24531f9bfc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_entrance', sa.Column('user_agent', sa.String(length=255), nullable=False))
    op.add_column('account_entrance', sa.Column('ip_addr', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'account_entrance', ['id', 'user_agent'])
    op.create_unique_constraint(None, 'user_social', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_social', type_='unique')
    op.drop_constraint(None, 'account_entrance', type_='unique')
    op.drop_column('account_entrance', 'ip_addr')
    op.drop_column('account_entrance', 'user_agent')
    # ### end Alembic commands ###
