version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
          discovery.type: "single-node"
    volumes:
      - elastic_volume:/var/lib/elasticsearch/data/
    ports:
      - "9200:9200"
    networks:
      - ugc

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - ugc

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044"
    volumes:
      - ./tmp/logs/nginx/:/var/log/nginx/:ro
      - ./configs/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - ugc

  nginx:
    build: ./configs/nginx
    container_name: nginx
    networks:
      - ugc
    volumes:
      - ./tmp/logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    volumes:
      - ./tmp/logs/nginx:/var/log/nginx:ro
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash
    networks:
      - ugc


networks:
  ugc:
    name: ugc
    driver: bridge


volumes:
  elastic_volume: