name: UGC_2
on:
  push:
    branches: [ "main" ]
    paths:
      - 'ugc/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ugc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create directories
      run: |
        mkdir -p reports/flake/
        mkdir -p reports/mypy/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml types-requests types-python-dateutil
        pip install wemake-python-styleguide flake8-html mypy
        
      


    - name: Lint with wemake-python-styleguide
      run: |
        flake8 ugc --exit-zero --format=html --htmldir=reports/flake/
        flake8 notifications --exit-zero --format=html --htmldir=reports/flake/
    - name: Check with mypy
      run: |
        mypy ugc --ignore-missing-imports --html-report reports/mypy/
        mypy notifications --ignore-missing-imports --html-report reports/mypy/
    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
          name: reports
          path: reports/

  send_message:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
